// Empty-state CTA. baseline-ui: empty states must give one clear next action.
// PromptSuggestion chips give that action while also priming users on what
// kinds of prompts work well in this demo.

import { PromptSuggestion } from "@/components/ui/prompt-suggestion";

const SUGGESTIONS = [
  "Reply with the single word PONG.",
  "Explain Server Components in two sentences.",
  "Write a Python one-liner that flattens a nested list.",
  "What's new in the Claude Agent SDK?",
];

type ChatEmptyProps = {
  onPick: (prompt: string) => void;
  disabled?: boolean;
};

export function ChatEmpty({ onPick, disabled }: ChatEmptyProps) {
  return (
    <div className="mx-auto flex max-w-xl flex-col items-center gap-6 py-12 text-center">
      <div className="flex flex-col gap-2">
        <h2 className="text-balance text-xl font-semibold tracking-tight">
          Chat with your local Claude
        </h2>
        <p className="text-pretty text-sm text-muted-foreground">
          Every reply is generated by spawning the{" "}
          <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-[12px]">
            claude
          </code>{" "}
          CLI on this machine using its stored login. No API key in the loop.
        </p>
      </div>
      <div className="flex w-full flex-wrap items-center justify-center gap-2">
        {SUGGESTIONS.map((s) => (
          <PromptSuggestion
            key={s}
            size="sm"
            disabled={disabled}
            onClick={() => onPick(s)}
          >
            {s}
          </PromptSuggestion>
        ))}
      </div>
    </div>
  );
}
